name: Pipeline CI/CD

on:
  push:
    branches: [main, staging, develop]
  pull_request:
    branches: [main, staging, develop]
    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
jobs:
  execute:
    uses: AYTECOL/devops-toolkit-central-templates/.github/workflows/frontend-orchestrator-workflow.yml@main
    with:
      node-version: "22.12.0" # Definimos la versión aquí
      disabled-test: false # Cambiar a true si no hay tests
      disabled-deploy: false # Cambiar a true si la infra no existe
    secrets: inherit
