name: Deploy Infrastructure

on:
  push:
    branches: [main, staging, develop]
    paths:
      - 'infrastructure/**'
  pull_request:
    branches: [main, staging, develop]
    paths:
      - 'infrastructure/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  execute:
    uses: AYTECOL/devops-toolkit-central-templates/.github/workflows/cloudformation-orchestrator-workflow.yml@main
    with:
      capabilities: "CAPABILITY_IAM,CAPABILITY_NAMED_IAM"
      wait-for-completion: true
      timeout: 10 # timeout for completion
    secrets: inherit


